import type { Metadata } from "next";
import { Source_Sans_3, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const fontSans = Source_Sans_3({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${fontMono.variable} antialiased`}
      >
        {/* <header className="border-b border-white">
          <nav>
            <Link href="/" className="p-4">
              Home
            </Link>
            <Link href="/admin" className="p-4">
              Admin
            </Link>
            <Link href="/admin/order" className="p-4">
              Order
            </Link>
            <Link href="/about" className="p-4">
              About
            </Link>
          </nav>
        </header> */}
        {children}
      </body>
    </html>
  );
}
