import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b border-white">
          <nav>
            <Link href="/" className="p-4">
              Home
            </Link>
            <Link href="/admin" className="p-4">
              Admin
            </Link>
            <Link href="/admin/order" className="p-4">
              Order
            </Link>
            <Link href="/about" className="p-4">
              About
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
